package statemachine.utils;

public enum StateName {
	START, SETUP, RETRIEVE_RECOMMENDATIONS, DASHBOARD, ADD_FILE, RETRIEVE_FILE_QUERY, 
	RETRIEVING_FILE, RATING, VIEWING_FILES, REFRESH, CLICK_YES, CLICK_NO, CLICK_BACK, CLICK_FILE, CLICK_SUBMIT, INIT, LOADING_FILES;
}